import type { Opportunity } from './types'

// ── Generators ────────────────────────────────────────────────────────────────

export function opportunityToMarkdown(opp: Opportunity): string {
  const lines: string[] = []
  const evidence = Array.isArray(opp.evidence) ? opp.evidence : opp.evidence ? [opp.evidence] : []

  lines.push(`# ${opp.name ?? 'Unnamed Opportunity'}`)
  lines.push('')
  if (opp.score != null) lines.push(`**Score:** ${opp.score.toFixed(2)}`)
  if (opp.rank  != null) lines.push(`**Rank:** #${opp.rank}`)
  lines.push(`**Status:** ${opp.user_status}`)
  lines.push('')

  if (opp.problem) {
    lines.push('## Problem', '', opp.problem, '')
  }

  if (evidence.length > 0) {
    lines.push('## Evidence', '')
    evidence.forEach(e => lines.push(`- ${e}`))
    lines.push('')
  }

  if (opp.target_user)   lines.push('## Target User',   '', opp.target_user,   '')
  if (opp.monetization)  lines.push('## Monetization',  '', opp.monetization,  '')
  if (opp.build_time)    lines.push(`**Build Time:** ${opp.build_time}`, '')

  const mvp = opp.mvp_features ?? []
  if (mvp.length > 0) {
    lines.push('## MVP Features', '')
    mvp.forEach(f => lines.push(`- ${f}`))
    lines.push('')
  }

  if (opp.scoring) {
    lines.push('## Scoring Breakdown', '')
    lines.push('| Criterion | Score | Weight |')
    lines.push('|---|---|---|')
    lines.push(`| Pain intensity   | ${opp.scoring.pain_intensity  ?? '-'} | 30% |`)
    lines.push(`| Trend momentum   | ${opp.scoring.trend_momentum  ?? '-'} | 20% |`)
    lines.push(`| Competition gap  | ${opp.scoring.competition_gap ?? '-'} | 25% |`)
    lines.push(`| MVP feasibility  | ${opp.scoring.mvp_feasibility ?? '-'} | 25% |`)
    lines.push('')
  }

  if (opp.reasoning) lines.push('## LLM Reasoning', '', opp.reasoning, '')
  if (opp.notes)     lines.push('## Personal Notes', '', opp.notes,     '')

  lines.push('---', '_Generated by FoundryScan_')
  return lines.join('\n')
}

export function opportunityToText(opp: Opportunity): string {
  const lines: string[] = []
  const evidence = Array.isArray(opp.evidence) ? opp.evidence : opp.evidence ? [opp.evidence] : []
  const HR = '-'.repeat(48)

  lines.push((opp.name ?? 'Unnamed Opportunity').toUpperCase())
  lines.push('='.repeat(48))
  lines.push('')
  if (opp.score != null) lines.push(`Score:  ${opp.score.toFixed(2)}`)
  if (opp.rank  != null) lines.push(`Rank:   #${opp.rank}`)
  lines.push(`Status: ${opp.user_status}`)
  lines.push('')

  if (opp.problem) {
    lines.push('PROBLEM', HR, opp.problem, '')
  }

  if (evidence.length > 0) {
    lines.push('EVIDENCE', HR)
    evidence.forEach(e => lines.push(`• ${e}`))
    lines.push('')
  }

  if (opp.target_user)  lines.push('TARGET USER',  HR, opp.target_user,  '')
  if (opp.monetization) lines.push('MONETIZATION', HR, opp.monetization, '')
  if (opp.build_time)   lines.push(`Build Time: ${opp.build_time}`, '')

  const mvp = opp.mvp_features ?? []
  if (mvp.length > 0) {
    lines.push('MVP FEATURES', HR)
    mvp.forEach(f => lines.push(`• ${f}`))
    lines.push('')
  }

  if (opp.scoring) {
    lines.push('SCORING', HR)
    lines.push(`Pain intensity:   ${opp.scoring.pain_intensity  ?? '-'} (30%)`)
    lines.push(`Trend momentum:   ${opp.scoring.trend_momentum  ?? '-'} (20%)`)
    lines.push(`Competition gap:  ${opp.scoring.competition_gap ?? '-'} (25%)`)
    lines.push(`MVP feasibility:  ${opp.scoring.mvp_feasibility ?? '-'} (25%)`)
    lines.push('')
  }

  if (opp.reasoning) lines.push('LLM REASONING', HR, opp.reasoning, '')
  if (opp.notes)     lines.push('PERSONAL NOTES', HR, opp.notes, '')

  lines.push('Generated by FoundryScan')
  return lines.join('\n')
}

// ── Download trigger ──────────────────────────────────────────────────────────

export function downloadText(content: string, filename: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadOpportunity(opp: Opportunity, format: 'md' | 'txt') {
  const slug = (opp.name ?? 'opportunity')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .slice(0, 60)
  if (format === 'md') {
    downloadText(opportunityToMarkdown(opp), `${slug}.md`, 'text/markdown')
  } else {
    downloadText(opportunityToText(opp), `${slug}.txt`, 'text/plain')
  }
}
